import Anthropic from "@anthropic-ai/sdk";
import { betaZodOutputFormat } from "@anthropic-ai/sdk/helpers/beta/zod";
import type { StrategyHypothesis, StrategyInferenceRequest, StrategyInferenceRun } from "@/lib/types";
import { getProject } from "@/lib/projects";
import { AI_CONFIG, hasAnthropicApiKey } from "@/lib/server/ai/config";
import { getAnthropicClient } from "@/lib/server/ai/client";
import { AnalysisError } from "@/lib/server/product-analysis/errors";
import { mapAnthropicError, type AnthropicLike } from "@/lib/server/product-analysis/analyzers";
import { GLOBAL_CREATIVE_CONSTITUTION } from "@/lib/prompts/global-creative-constitution";
import { assessHypothesis } from "@/lib/strategy/strategy-guards";
import { buildStrategyInputs, fingerprint, strategyInputKey, type StrategyInputs } from "@/lib/strategy/strategy-inputs";
import { STRATEGY_SYSTEM_PROMPT, buildStrategyUserText } from "./prompt";
import { StrategyOutputSchema, parseStrategyOutput, toHypotheses } from "./schema";

/**
 * inferStrategy() — SAFE PROFILE + BRAND + ASSETS + CONSTITUTION → STRATEGY HYPOTHESES.
 *
 * One explicit "Generate AI hypotheses" action = exactly one model call.
 * Only CreativeSafeProductProfile content reaches the model (withheld items
 * are used solely to drop hypotheses that would restate them).
 */

export interface InferDeps {
  createClient?: () => AnthropicLike;
  now?: () => number;
}

interface InferResult {
  hypotheses: StrategyHypothesis[];
  unknowns: string[];
  dropped: StrategyInferenceRun["dropped"];
  warnings: string[];
  model: string | null;
  modelCalls: number;
  usage: StrategyInferenceRun["usage"];
}

async function runModel(client: AnthropicLike, inputs: StrategyInputs, request: StrategyInferenceRequest, runId: string): Promise<InferResult> {
  const cfg = AI_CONFIG.strategyInference;
  let response;
  try {
    response = await client.beta.messages.parse({
      model: cfg.model,
      max_tokens: cfg.maxTokens,
      betas: ["server-side-fallback-2026-07-01"],
      fallbacks: "default",
      output_config: { effort: cfg.effort, format: betaZodOutputFormat(StrategyOutputSchema) },
      system: STRATEGY_SYSTEM_PROMPT,
      messages: [{ role: "user", content: buildStrategyUserText(inputs, GLOBAL_CREATIVE_CONSTITUTION) }],
    });
  } catch (err) {
    throw mapAnthropicError(err);
  }

  if (response.stop_reason === "refusal") throw new AnalysisError("ai_refused");
  if (response.stop_reason === "max_tokens") throw new AnalysisError("invalid_ai_output", "The strategy was cut off before completion.");

  let raw: unknown = response.parsed_output;
  if (raw == null) {
    const text = response.content.flatMap((b) => (b.type === "text" ? [b.text] : [])).join("");
    try {
      raw = JSON.parse(text);
    } catch {
      throw new AnalysisError("invalid_ai_output", "The response was not valid JSON.");
    }
  }
  const validated = toHypotheses(parseStrategyOutput(raw), { runId, inputs, safeProfile: request.safeProfile, brand: request.brandStrategy });
  return {
    ...validated,
    model: response.model ?? cfg.model,
    modelCalls: 1,
    usage: response.usage ? { inputTokens: response.usage.input_tokens, outputTokens: response.usage.output_tokens } : null,
  };
}

/** Demo mode: the workspace's stored hypotheses, run through the same guards. No network, no AI. */
function runMock(request: StrategyInferenceRequest, runId: string): InferResult {
  const hypotheses = getProject(request.projectId).hypotheses.map((h) => assessHypothesis({ ...h, id: `${runId}_${h.id}`, runId, reviewStatus: "unreviewed", approvedByUser: false }, request.brandStrategy));
  return { hypotheses, unknowns: [], dropped: [], warnings: ["Demo hypotheses from the workspace — not generated by AI."], model: null, modelCalls: 0, usage: null };
}

export async function inferStrategy(request: StrategyInferenceRequest, deps: InferDeps = {}): Promise<StrategyInferenceRun> {
  const now = deps.now ?? Date.now;
  const started = now();
  if (request.analyzer === "real" && !deps.createClient && !hasAnthropicApiKey()) throw new AnalysisError("missing_api_key");

  const inputs = buildStrategyInputs(request.safeProfile, request.brandStrategy, request.direction);
  const inputKey = strategyInputKey(inputs);
  const createdAt = new Date(started).toISOString();
  const runId = `run_${fingerprint(`${inputKey}:${createdAt}:${request.analyzer}`)}`;

  const result =
    request.analyzer === "mock" ? runMock(request, runId) : await runModel((deps.createClient ?? (getAnthropicClient as () => Anthropic))(), inputs, request, runId);

  return {
    id: runId,
    origin: request.analyzer === "mock" ? "mock" : "ai",
    model: result.model,
    createdAt,
    inputKey,
    safeProfileId: request.safeProfile.id,
    brandStrategyId: request.brandStrategy.id,
    hypotheses: result.hypotheses,
    unknowns: result.unknowns,
    dropped: result.dropped,
    warnings: result.warnings,
    modelCalls: result.modelCalls,
    durationMs: Math.max(0, now() - started),
    usage: result.usage,
  };
}
