import type { HypothesisCategory, HypothesisDecision, SourcedStatement, StrategyHypothesis } from "@/lib/types";
import { userInput } from "./provenance";

/**
 * STRATEGY HYPOTHESES — "What does AI think may be strategically relevant?"
 *
 * Generated by the AI when brand or product information is missing. Always
 * source = ai_inference with a confidence. They are the lowest-priority input
 * and never become facts. A user can accept (promotes to user_input) or
 * reject (drops) each hypothesis.
 */

/** Hypotheses below this confidence are shown but not used unless accepted. */
export const MIN_HYPOTHESIS_CONFIDENCE = 0.65;

export const HYPOTHESIS_CATEGORY_LABELS: Record<HypothesisCategory, string> = {
  customer_desire: "Customer desire",
  objection: "Objection",
  audience: "Audience",
  purchase_motivation: "Purchase motivation",
  positioning: "Positioning",
  messaging_angle: "Messaging angle",
  visual_opportunity: "Visual opportunity",
  creative_opportunity: "Creative opportunity",
};

export function applyDecisions(
  hypotheses: StrategyHypothesis[],
  decisions: Record<string, HypothesisDecision> = {},
): StrategyHypothesis[] {
  return hypotheses.map((h) => (decisions[h.id] ? { ...h, decision: decisions[h.id] } : h));
}

export function isUsable(h: StrategyHypothesis) {
  if (h.decision === "rejected") return false;
  return h.decision === "accepted" || h.confidence >= MIN_HYPOTHESIS_CONFIDENCE;
}

/** Hypotheses of the given categories as sourced statements, respecting decisions. */
export function hypothesisStatements(hypotheses: StrategyHypothesis[], ...categories: HypothesisCategory[]): SourcedStatement[] {
  return hypotheses
    .filter((h) => categories.includes(h.category) && isUsable(h))
    .map((h) =>
      h.decision === "accepted"
        ? { ...userInput(h.statement, h.id), rationale: `Accepted AI hypothesis: ${h.rationale}` }
        : { statement: h.statement, source: "ai_inference", confidence: h.confidence, rationale: h.rationale, sourceRef: h.id },
    );
}
